apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
  labels:
    app: weatherapp
spec:
  type: NodePort
  selector:
    app: weatherapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


# kubectl get svc weatherapp-service to figure out the port