---
- name: pull image
  docker_image:
    name: {{ docker_image_name }}
    source: pull
    state: present

- name: run container
  docker_container:
    name: advisor
    image: kchauntell/advisor:***** #need to get
    state: started
    ports:
      - "8080:8080"
    restart_policy: always
    detach: yes